import "@/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { Providers } from "@/app/_components/providers";
import { getServerAuthSession } from "@/server/auth";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Music Sharing Project",
  description: "Generated by create-t3-app - Fair enough",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();

  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <Providers
          Session={{ session }}
          Theme={{
            attribute: "class",
            defaultTheme: "dark",
            enableSystem: true,
            disableTransitionOnChange: true,
          }}
        >
          <div className="mx-auto min-h-screen max-w-[700px] border-x border-neutral-400 border-opacity-25">
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </div>
        </Providers>
      </body>
    </html>
  );
}
